// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtIk5y_XDfFcwFDnCUpGSs4jODeDU-glY',
    appId: '1:745187141866:web:333d272307e3e9c5460f93',
    messagingSenderId: '745187141866',
    projectId: 'rebuy-29f76',
    authDomain: 'rebuy-29f76.firebaseapp.com',
    storageBucket: 'rebuy-29f76.firebasestorage.app',
    measurementId: 'G-XJ1WCY1DTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1r6MO8nLpN1IY7GbIRScP2cVK-On3FsM',
    appId: '1:745187141866:android:0df71107236fa880460f93',
    messagingSenderId: '745187141866',
    projectId: 'rebuy-29f76',
    storageBucket: 'rebuy-29f76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwqnDC6R2FHBGKqnQBsOUnsOazWqP9924',
    appId: '1:745187141866:ios:ef35998a92964a46460f93',
    messagingSenderId: '745187141866',
    projectId: 'rebuy-29f76',
    storageBucket: 'rebuy-29f76.firebasestorage.app',
    iosBundleId: 'com.example.rebuy',
  );
}
